### PR TITLE
Fix for preview-menu being hidden

### LINKED ISSUE #8: Preview-menu is hidden by other UI elements when using Indigo
Hey,

As discussed [here](https://github.com/overhangio/indigo/pull/7#issuecomment-704352136) there's an issue for staff/admin users that Indigo hides the dropdown menu to view courses as learner or specific learners (etc) behind the global header. This can be fixed by removing `position: fixed` and change `overflow: visible` to `overflow: hidden` in _extras.scss

### PR DESCRIPTION
**Pull request by Doppern**
Closes #8

### CODE REVIEW

**Comment by regisb** [comment]
Thanks for this PR @Doppern! I would like to keep the `header.global-header` position fixed, such that it stays on top of the screen when the user scrolls down (on large screens only). Do you think you could achieve that?

**Comment by Doppern** [comment]
Maybe a bit clunky - CSS is hardly my specialty, but it seems to work by adding the same properties to the preview-menu.

**Comment by regisb** [comment]
I found a simpler fix ;) https://github.com/overhangio/indigo/commit/62cbabcd625bb1b81f009b0052dc81f483be3218

**Comment by Doppern** [comment]
That looks more elegant indeed - unfortunately the menu only shows on the "Front page" of a course, and not on all pages, the `margin-top: 75px;` doesn't get added on all pages for some reason (I assume the way the SASS is processed?) so this is not a complete fix.

**Comment by regisb** [comment]
Indeed @Doppern, I can verify what you are describing. This issue is visible here: https://demo.openedx.overhang.io/courses/course-v1:edX+DemoX+Demo_Course/courseware/interactive_demonstrations/19a30717eff543078a5d94ae9d6c18a5/?activate_block_id=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40sequential%2Bblock%4019a30717eff543078a5d94ae9d6c18a5
My understanding is that the CSS rule is being overridden by a higher priority rule which states `margin: 0`. This can be resolved by making the css rule even more precise -- e.g: `.wrapper-preview-menu --> nav.wrapper-preview-menu`. I'll push another fix.

**Pull request closed without merging**
